import { getCurrentUser } from "@/lib/actions/user.actions";
import type { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const getAuthorizedUser = await getCurrentUser();
  
  // if (!getAuthorizedUser) redirect("/sign-in");
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
